# -*- coding: utf-8 -*-
"""517POAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqRXOwE-HevTheVRpCVFDR6F3EBR9U6W
"""

my_list = [10, 20, 30, 40, 50]


element_to_find = 30


if element_to_find in my_list:
    index = my_list.index(element_to_find)
    print(f"The index of {element_to_find} is {index}.")
else:
    print(f"{element_to_find} is not in the list.")

a=10
b=20
if(a>b):
  print(f"{a} is greater than {b}")
elif(b>a):
  print(f"{b} is greater than {a}")
else:
  print("Both are equal")

my_list = [10, 20, 30, 40, 50, 8, 8, 10, 30, 8 ,8]
element_to_count = 8

count = my_list.count(element_to_count)
print(f"The element {element_to_count} appears {count} times in the list.")

def is_palindrome(text):
  text = text.lower().replace(" ", "")
  return text == text[::-1]

text = "hoh"

if is_palindrome(text):
  print("It's a palindrome!")
else:
  print("It's not a palindrome.")

my_list = [10, 20, 30, 40, 50]
remove = 30

if remove in my_list:
  my_list.remove(remove)
  print(f"The element {remove} has been removed from the list.")
  print("Updated list:", my_list)
else:
  print(f"The element {remove} is not in the list.")

list1 = [1, 2, 3]
list2 = [4, 5, 6]

combinedlist = list1 + list2
count = len(combinedlist)

print("Combined list:", combinedlist)
print("Count of elements:", count)

list1 = [1, 2, 3]
list2 = [4, 5, 6]

result = []
for i in range(len(list1)):
  result.append(list1[i] + list2[i])

print("Sum of elements at corresponding positions:", result)

list1 = [1, 2, 3]
list2 = [4, 5, 6]

list1, list2 = list2, list1

print("List 1:", list1)
print("List 2:", list2)

my_list = [10, 20, 30, 40, 50]
my_list.reverse()
print("Reversed list:", my_list)

text = "This is a sample text."
vowels = "aeiouAEIOU"
vowel_count = 0

for char in text:
  if char in vowels:
    vowel_count += 1

print("Number of vowels:", vowel_count)